import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { map } from 'rxjs/operators';

import { User, UserDeserialized } from 'src/app/shared/models/user';

const data1 = JSON.parse(`[{"id":"1","name":"Grayson Wiegand","userInfo":{"weightKG":85,"favouriteHobby":"None"},"cars":[{"id":"1","userId":"1","make":"Morissette LLC","model":"Fantastic Metal Chicken","color":"red","carSpecs":{"powerBHP":250}},{"id":"6","userId":"1","make":"Schuppe Group","model":"Fantastic Plastic Towels","color":"teal","carSpecs":{"powerBHP":1000}},{"id":"11","userId":"1","make":"Osinski Group","model":"Intelligent Cotton Pizza","color":"purple","carSpecs":{"powerBHP":189}}]},{"id":"2","name":"Forest Stiedemann","userInfo":{"weightKG":50,"favouriteHobby":"Drifting"},"cars":[{"id":"2","userId":"2","make":"Parisian, Shields and Sanford","model":"Sleek Fresh Pants","color":"pink","carSpecs":{"powerBHP":666}},{"id":"7","userId":"2","make":"Larkin - Collins","model":"Intelligent Soft Mouse","color":"olive","carSpecs":{"powerBHP":701}},{"id":"12","userId":"2","make":"Bailey Inc","model":"Fantastic Wooden Keyboard","color":"purple","carSpecs":{"powerBHP":350}}]},{"id":"3","name":"Catherine Graham","userInfo":{"weightKG":47,"favouriteHobby":"Sportsball"},"cars":[{"id":"3","userId":"3","make":"Jenkins - Rutherford","model":"Tasty Rubber Towels","color":"lavender","carSpecs":{"powerBHP":349}},{"id":"8","userId":"3","make":"Brekke - Hegmann","model":"Practical Soft Shoes","color":"turquoise","carSpecs":{"powerBHP":450}}]},{"id":"4","name":"Triston Tremblay","userInfo":{"weightKG":74,"favouriteHobby":"Guitar"},"cars":[{"id":"4","userId":"4","make":"Powlowski - Kreiger","model":"Tasty Rubber Fish","color":"tan","carSpecs":{"powerBHP":220}},{"id":"9","userId":"4","make":"Yost, Swift and Corwin","model":"Unbranded Granite Tuna","color":"mint green","carSpecs":{"powerBHP":650}}]},{"id":"5","name":"Dr. Johnathon Price","userInfo":{"weightKG":69,"favouriteHobby":"Cricket"},"cars":[{"id":"5","userId":"5","make":"Ruecker, Romaguera and Upton","model":"Rustic Metal Keyboard","color":"orange","carSpecs":{"powerBHP":156}},{"id":"10","userId":"5","make":"Harris - Mraz","model":"Fantastic Fresh Shoes","color":"tan","carSpecs":{"powerBHP":245}}]}]`);
const data2 = JSON.parse(`[{"id":"1","name":"Grayson Wiegand","userInfo":{"weightKG":85,"favouriteHobby":"None"},"cars":[{"id":"1","userId":"1","make":"Morissette LLC","model":"Fantastic Metal Chicken","color":"red","carSpecs":{"powerBHP":250}},{"id":"6","userId":"1","make":"Schuppe Group","model":"Fantastic Plastic Towels","color":"teal","carSpecs":{"powerBHP":1000}},{"id":"11","userId":"1","make":"Osinski Group","model":"Intelligent Cotton Pizza","color":"purple","carSpecs":{"powerBHP":189}}]},{"id":"2","name":"Forest Stiedemann","userInfo":{"weightKG":50,"favouriteHobby":"Drifting"},"cars":[{"id":"2","userId":"2","make":"Parisian, Shields and Sanford","model":"Sleek Fresh Pants","color":"pink","carSpecs":{"powerBHP":666}},{"id":"7","userId":"2","make":"Larkin - Collins","model":"Intelligent Soft Mouse","color":"olive","carSpecs":{"powerBHP":701}},{"id":"12","userId":"2","make":"Bailey Inc","model":"Fantastic Wooden Keyboard","color":"purple","carSpecs":{"powerBHP":350}}]},{"id":"3","name":"Catherine Graham","userInfo":{"weightKG":47,"favouriteHobby":"Sportsball"},"cars":[{"id":"3","userId":"3","make":"Jenkins - Rutherford","model":"Tasty Rubber Towels","color":"lavender","carSpecs":{"powerBHP":349}},{"id":"8","userId":"3","make":"Brekke - Hegmann","model":"Practical Soft Shoes","color":"turquoise","carSpecs":{"powerBHP":450}}]},{"id":"4","name":"Triston Tremblay","userInfo":{"weightKG":74,"favouriteHobby":"Guitar"},"cars":[{"id":"4","userId":"4","make":"Powlowski - Kreiger","model":"Tasty Rubber Fish","color":"tan","carSpecs":{"powerBHP":220}},{"id":"9","userId":"4","make":"Yost, Swift and Corwin","model":"Unbranded Granite Tuna","color":"mint green","carSpecs":{"powerBHP":650}}]},{"id":"5","name":"Dr. Johnathon Price","userInfo":{"weightKG":69,"favouriteHobby":"Cricket"},"cars":[{"id":"5","userId":"5","make":"Ruecker, Romaguera and Upton","model":"Rustic Metal Keyboard","color":"orange","carSpecs":{"powerBHP":156}},{"id":"10","userId":"5","make":"Harris - Mraz","model":"Fantastic Fresh Shoes","color":"tan","carSpecs":{"powerBHP":245}}]}]`);
const data3 = JSON.parse(`[{"id":"1","name":"Grayson Wiegand","userInfo":{"weightKG":85,"favouriteHobby":"None"},"cars":[{"id":"1","userId":"1","make":"Morissette LLC","model":"Fantastic Metal Chicken","color":"red","carSpecs":{"powerBHP":250}},{"id":"6","userId":"1","make":"Schuppe Group","model":"Fantastic Plastic Towels","color":"teal","carSpecs":{"powerBHP":1000}},{"id":"11","userId":"1","make":"Osinski Group","model":"Intelligent Cotton Pizza","color":"purple","carSpecs":{"powerBHP":189}}]},{"id":"2","name":"Forest Stiedemann","userInfo":{"weightKG":50,"favouriteHobby":"Drifting"},"cars":[{"id":"2","userId":"2","make":"Parisian, Shields and Sanford","model":"Sleek Fresh Pants","color":"pink","carSpecs":{"powerBHP":666}},{"id":"7","userId":"2","make":"Larkin - Collins","model":"Intelligent Soft Mouse","color":"olive","carSpecs":{"powerBHP":701}},{"id":"12","userId":"2","make":"Bailey Inc","model":"Fantastic Wooden Keyboard","color":"purple","carSpecs":{"powerBHP":350}}]},{"id":"3","name":"Catherine Graham","userInfo":{"weightKG":47,"favouriteHobby":"Sportsball"},"cars":[{"id":"3","userId":"3","make":"Jenkins - Rutherford","model":"Tasty Rubber Towels","color":"lavender","carSpecs":{"powerBHP":349}},{"id":"8","userId":"3","make":"Brekke - Hegmann","model":"Practical Soft Shoes","color":"turquoise","carSpecs":{"powerBHP":450}}]},{"id":"4","name":"Triston Tremblay","userInfo":{"weightKG":74,"favouriteHobby":"Guitar"},"cars":[{"id":"4","userId":"4","make":"Powlowski - Kreiger","model":"Tasty Rubber Fish","color":"tan","carSpecs":{"powerBHP":220}},{"id":"9","userId":"4","make":"Yost, Swift and Corwin","model":"Unbranded Granite Tuna","color":"mint green","carSpecs":{"powerBHP":650}}]},{"id":"5","name":"Dr. Johnathon Price","userInfo":{"weightKG":69,"favouriteHobby":"Cricket"},"cars":[{"id":"5","userId":"5","make":"Ruecker, Romaguera and Upton","model":"Rustic Metal Keyboard","color":"orange","carSpecs":{"powerBHP":156}},{"id":"10","userId":"5","make":"Harris - Mraz","model":"Fantastic Fresh Shoes","color":"tan","carSpecs":{"powerBHP":245}}]}]`);

@Injectable({
    providedIn: 'root',
})
export class UserService {
  constructor(private http: HttpClient) {}

  public getUsersJson(): Observable<User[]> {
    return of(data1);
    // const url = 'https://5f62b20867e195001625f124.mockapi.io/user';
    // return this.http.get<User[]>(url);
  }

  public getUsersConstructor(): Observable<User[]> {
    return of(data2).pipe(map((result) => result.map(user => new User(user))));
    // const url = 'https://5f62b20867e195001625f124.mockapi.io/user';
    // return this.http.get<User[]>(url).pipe(map((result) => result.map(user => new User(user))));
  }

  public getUsersDeserialize(): Observable<UserDeserialized[]> {
    return of(data3).pipe(map((result) => result.map(user => new UserDeserialized().deserialize(user))));
    // const url = 'https://5f62b20867e195001625f124.mockapi.io/user';
    // return this.http.get<UserDeserialized[]>(url).pipe(map((result) => result.map(user => new UserDeserialized().deserialize(user))));
  }
}
